name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/') }}

      - name: Gradle build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: |
            conreg-cli/build/libs/*.jar
          retention-days: 5

  build-native:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact: app-native-linux
          - os: windows-latest
            artifact: app-native-windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: "true"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/') }}

      - name: Gradle nativeCompile
        run: ./gradlew nativeCompile

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: |
            conreg-cli/build/native/nativeCompile
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: [ build-jvm, build-native ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Prepare Linux Artifacts
        run: |
          cd app-native-linux
          chmod +x conreg
          tar -czf $(cat gradle-artifact.txt)-linux-amd64.tar.gz conreg

      - name: Prepare Windows Artifacts
        run: |
          cd app-native-windows
          zip $(cat gradle-artifact.txt)-windows-amd64.zip conreg.exe

      - name: Build Release Changelog
        id: build-release-changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/release-changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build-release-changelog.outputs.changelog }}
          draft: true
          files: |
            app-jar/**/*-all.jar
            app-native-linux/*.tar.gz
            app-native-windows/*.zip

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          cache-read-only: ${{ github.ref != 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
#
#      - name: Gradle publish
#        env:
#          OSSRH_USER: ${{ secrets.OSSRH_USER }}
#          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
#        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
